name: UI Build, Lint, Format, and Test

on:
  pull_request:
    branches: [master]

jobs:
  ui-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format

      - name: Run tests
        run: npm run test

      - name: Build UI
        run: npm run build
